Add missing Tickers type
We are currently receiving the following compile error:

```
../go-hitbtc/hitbtc.go:121:42: undefined: Tickers
```

This type was probably forgotten to be included when PR #6 was merged:

https://github.com/bitbandi/go-hitbtc/pull/6